[package]
name = "slack-emoji-exporter"
version = "0.1.0"
authors = ["Anthony Scotti <anthony.m.scotti@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = "0.11.0"